# Site Settings
title:               Andrew Campbell
tagline:             a programmers mind
description:
baseurl:            #"/AndrewCampbell17"
url:                #"https://AndrewCampbell17.github.io"
github:
  url:               #"https://AndrewCampbell17.github.io"
author:
  name:              "Andrew Campbell"
  email:             "AndrewCampbell94@Outlook.com"
  twitter:           "Androoodles"
  instagram:         "acampbell0517"
  github:            "AndrewCampbell17"
  facebook:          "AndrewCampbell22"
  linkedin:          "andrew-campbell-534ba6124"
navigation:
- title: About
  url: /about
- title: Writing
  url: /writing
- title: Contact
  url: /contact

paginate:            5
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
